# Generated by Django 2.2.1 on 2019-05-07 12:44

from django.db import migrations, models
import scheduler_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cron_task',
            field=models.CharField(blank=True, max_length=50, validators=[scheduler_app.validators.validate_5_segments_or_not]),
        ),
    ]
