# Generated by Django 2.2.1 on 2019-07-24 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0011_auto_20190508_0153'),
        ('scheduler_app', '0003_auto_20190508_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='periodic_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('passed', 'Passed')], default='new', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='task_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
